config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :friendships

  resources :comments
  resources :recipes
  resources :users
  resources :sessions

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  get '/sign_up' => 'users#new', as: :sign_up

  root 'recipes#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name:'User'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    redirect_to login_path unless current_user
    @friendship = current_user.friendships.build(friend_id:params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to :back, notice: "Added friend #{@friendship.friend.name} successfully." }
        format.json { render json: @friendship, status: :created }
      else
        # format.html { render action: 'new' }
        format.html { redirect_to :back, alert: 'Errors of creating friendship: '+@friendship.errors.full_messages.join('\n') }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice:"Remoe friend #{@friendship.friend.name} successfully." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.haml
= simple_form_for(@friendship) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.association :friend

  .form-actions
    = f.button :submit

app/views/friendships/create.html.haml
.page-header
  %h1 Friendships#create
%p Find me in app/views/friendships/create.html.haml

app/views/friendships/destroy.html.haml
.page-header
  %h1 Friendships#destroy
%p Find me in app/views/friendships/destroy.html.haml

app/views/friendships/edit.html.haml
.page-header
  = link_to friendships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @friendship, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing friendship

= render 'form'

app/views/friendships/index.html.haml
.page-header
  = link_to new_friendship_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Friendship
  %h1 Listing friendships

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th User
        %th Friend
        %th
        %th
        %th

    %tbody
      - @friendships.each do |friendship|
        %tr
          %td= friendship.user
          %td= friendship.friend
          %td= link_to 'Show', friendship
          %td= link_to 'Edit', edit_friendship_path(friendship)
          %td= link_to 'Destroy', friendship, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/friendships/new.html.haml
.page-header
  = link_to friendships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New friendship

= render 'form'

app/views/friendships/show.html.haml
.page-header
  = link_to friendships_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_friendship_path(@friendship), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show friendship

%dl.dl-horizontal
  %dt User:
  %dd= @friendship.user
  %dt Friend:
  %dd= @friendship.friend