config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :friendships

  resources :comments
  resources :recipes
  resources :users
  resources :sessions

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  get '/sign_up' => 'users#new', as: :sign_up

  root 'recipes#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :trackable, polymorphic: true

  # belongs_to :comment, ->{includes(:activities).references(:activities)}, foreign_key: :trackable_id

  belongs_to :comment, foreign_key: :trackable_id
  belongs_to :recipe, foreign_key: :trackable_id
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.order('created_at desc').
        includes(:owner, comment: {recipe: :user}, recipe: :user)
  end

  def friend
    redirect_to(:login_url, alert:'Log in first.') unless current_user
    @activities = Activity.order('created_at desc').
        where(owner:current_user.friends).
        includes(:owner, comment: {recipe: :user})
    render 'index'
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_comment.html.haml
%p
  =link_to activity.user.name, activity.user
  #{activity.action.sub(/e?$/,'ed')} a comment on
  - recipe =  activity.try(:comment).try(:recipe)
  - if recipe
    = link_to recipe.user.name, recipe.user
    's recipe
    = link_to recipe.name, recipe
  - else
    a recipe which has been removed.

app/views/activities/_form.html.haml
= simple_form_for(@activity) do |f|
  = f.error_notification

  .form-inputs
    = f.input :action
    = f.association :user
    = f.association :trackable

  .form-actions
    = f.button :submit

app/views/activities/_recipe.html.haml
%p
  =link_to activity.user.name, activity.user
  #{activity.action.sub(/e?$/,'ed')}
  - recipe =  activity.try(:recipe)
  - if recipe
    the recipe
    = link_to recipe.name, recipe
  - else
    a recipe which has been removed.

app/views/activities/edit.html.haml
.page-header
  = link_to activities_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @activity, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing activity

= render 'form'

app/views/activities/index.html.haml
.page-header
  -#= link_to new_activity_path, :class => 'btn btn-primary' do
  -#  %span.glyphicon.glyphicon-plus
  -#  New Activity
  %h1 Activities

- for activity in @activities
  = activity.decorate.render_activity

-#.table-responsive
-#  %table.table.table-striped.table-bordered.table-hover
-#    %thead
-#      %tr
-#        %th Action
-#        %th User
-#        %th Trackable
-#        %th
-#        %th
-#        %th
-#
-#    %tbody
-#      - @activities.each do |activity|
-#        %tr
-#          %td= activity.action
-#          %td= activity.user
-#          %td= activity.trackable
-#          %td= link_to 'Show', activity
-#          %td= link_to 'Edit', edit_activity_path(activity)
-#          %td= link_to 'Destroy', activity, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/activities/new.html.haml
.page-header
  = link_to activities_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New activity

= render 'form'

app/views/activities/show.html.haml
.page-header
  = link_to activities_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_activity_path(@activity), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show activity

%dl.dl-horizontal
  %dt Action:
  %dd= @activity.action
  %dt User:
  %dd= @activity.user
  %dt Trackable:
  %dd= @activity.trackable